esaude-metadata-tomcat:
  build: tomcat
  ports:
    - "8080:8080"
  container_name: esaude-metadata-tomcat
  links:
    - esaude-metadata-mysql
esaude-metadata-mysql:
  build: mysql
  ports:
    - "3306:3306"
  container_name: esaude-metadata-mysql